- name: install base packages
  package:
    name: "{{ package }}" 
    state: present 
  loop:
    - git
    - vim
    - libvirt 
    - httpd 
    - memcached 
    - bind 
  loop_control:
    loop_var: package
  become: true

- name: add the vagrant user to the libvirt group
  command: usermod --append --groups libvirt vagrant
  become: true
