- name: Debug vm info
  debug:
    var: vm_info

- name: Debug vm name 
  debug:
    var: vm_name

#- name: dbg 
#fail:
#msg: done

- name: set working directory
  file:
    path: "{{ working_dir }}"
    state: directory

- name: set base image directory
  file:
    path: "{{ base_image_dir }}"
    state: directory

- name: Get Image
  include_tasks: get_image.yml
  vars:
    image: "{{ vm_info.image }}"
  #when: image_group is defined

- name: set vm disk directory
  file:
    path: "{{ vm_disk_dir }}"
    state: directory

- name: Set local image path
  set_fact:
    base_image: "{{ vm_info.image.name }}"
  when: vm_info.image.group is not defined

- name: Set vagrant cloud image path
  set_fact:
    base_image: "{{ vm_info.image.group }}/{{ vm_info.image.name }}/{{ image_version }}"
  when: vm_info.image.group is defined

- name: check base image exists
  stat:
    path: "{{ base_image_dir }}/{{ base_image }}"
  register:  base_image_stat

- name: fail if the base image has been removed
  fail:
    msg: "Base image not found at {{ base_image_dir }}/{{ base_image }}"
  when: not base_image_stat.stat.exists

- name: Set current disk path
  set_fact:
    disk_path: "{{ vm_disk_dir }}/{{ vm_name }}"

- name: Remove current disk image if it's still there
  file:
    path: "{{ disk_path }}"
    state: absent

- name: Debug vm info
  debug:
    var: vm_info

- name: Copy base image to disk image location
  copy:
    src: "{{ base_image_dir }}/{{ base_image }}"
    dest: "{{ disk_path }}"

- name: Resize base image
  command: "qemu-img resize {{ disk_path }} 40G"
  when: vm_info.resize is defined

- name: Create resize script
  template:
    src: "resize.sh.j2"
    dest: /tmp/resize.sh
  when: vm_info.resize is defined

- name: Resize base image filesystem
  command: "virt-customize -v -a {{ disk_path }} --run /tmp/resize.sh"
  when: vm_info.resize is defined

- name: Create user/key script
  template:
    src: "userkey.sh.j2"
    dest: /tmp/userkey.sh
  when: vm_info.ssh is defined

- name: Copy local ssh key into vm image
  command: "virt-customize -v -a {{ disk_path }} --copy-in {{ vm_info.ssh.pub_key }}:/tmp"
  when: vm_info.ssh is defined

- name: Check for vagrant user and add local ssh key
  command: "virt-customize -v -a {{ disk_path }} --run /tmp/userkey.sh"
  when: vm_info.ssh is defined

# Modify the vm definition to include the base image volume
- name: Create vm definition
  set_fact:
    current_vm: "{{ vm_info|combine({'name' : vm_name, 'volumes': [ { 'name': vm_name, 'type': 'file', 'file_path': vm_disk_dir, 'capacity': '40GB', 'disk_bus': vm_info.disk_bus | default('sata') }]}, recursive=True) }}"

- name: Debug vm definition
  debug:
    var: current_vm

- name: Create VM
  include_role:
    name: libvirt-vm
  vars:
    libvirt_vms: "{{ [ current_vm ] }}"
    libvirt_vm_uri: "qemu:///session"
    libvirt_vm_sudo: false 

- name: Get VM mac address
  shell: "virsh dumpxml {{ vm_name }} | grep 'mac address' | head -n 1 | cut -d \"'\" -f 2"
  register: vm_mac

- block:
  - name: Get VM XML if we didn't get a mac
    command: virsh dumpxml testvm
    register: virsh_dumpxml
  - name: Show VM XML if we didn't get a mac
    debug:
      var: virsh_dumpxml.stdout
  - name: Fail
    fail:
      msh: Failed to find VM mac address
  when: vm_mac.stdout == ""

- name: Wait for VM IP
  command: "arp -n"
  register: vm_ip_avail
  retries: "{{ vm_info.ssh_wait | default(10) }}"
  delay: 1
  until: vm_ip_avail.stdout | regex_search(vm_mac.stdout)

- name: Get VM IP address
  shell: "arp -n | grep {{ vm_mac.stdout }} | cut -d ' ' -f 1"
  register: vm_ip

- name: Set VM IP address fact
  set_fact: {"{{ vm_name }}_ip":"{{ vm_ip.stdout }}"}

- name: Add new vm to inventory
  add_host:
    name: "{{ vm_ip.stdout }}"
    groups: "{{ vm_info.groups | default([ vm_name, 'locum' ] ) }}"
    ssh_user: "{{ vm_info.ssh.user | default('vagrant') }}"
    ansible_user: "{{ vm_info.ssh.user | default('vagrant') }}"
    ansible_username: "{{ vm_info.ssh.user | default('vagrant') }}"
    ansible_ssh_user: "{{ vm_info.ssh.user | default('vagrant') }}"
    ansible_password: "{{ vm_info.ansible_password }}"
    ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    host_key_checking: false
    locum_roles: "{{ vm_info.roles }}"
  when: vm_info.ansible_password is defined

- name: Add new vm to inventory
  add_host:
    name: "{{ vm_ip.stdout }}"
    groups: "{{ vm_info.groups | default([ vm_name, 'locum' ] ) }}"
    ssh_user: "{{ vm_info.ssh.user | default('vagrant') }}"
    ansible_user: "{{ vm_info.ssh.user | default('vagrant') }}"
    ansible_username: "{{ vm_info.ssh.user | default('vagrant') }}"
    ansible_ssh_user: "{{ vm_info.ssh.user | default('vagrant') }}"
    ansible_ssh_host: "{{ vm_ip.stdout }}"
    ansible_private_key_file: "{{ vm_info.ssh.pub_key | default(vagrant_private_key_path) }}"
    ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    host_key_checking: false
    locum_roles: "{{ vm_info.roles }}"
  when: vm_info.ansible_password is not defined

- name: Create ssh config
  template:
    src: "ssh_config.j2"
    dest: "{{ lookup( 'env', 'PWD') }}/.{{ vm_name }}_ssh_config"

- name: Set VM name fact
  set_fact:
    current_vm_name: "{{ vm_name }}"

#- name: configure local vm 
#include_tasks: local_roles.yml
#with_items: "{{ vm_info.roles }}"
#loop: "{{ vm_info.roles|flatten(levels=1) }}"
#loop_control:
#loop_var: vm_role
